Update project.html, project.css. Make media screen for desktop
Dutko-Diana/super-team-project pull request #3
Opened 2024-12-21 00:08 UTC by tetiana-haievska

2024-12-21 10:11 UTC, Dutko-Diana requested changes
МОБІЛЬНА ВЕРСІЯ
1. Потрібно поміняти формат media в тегу picture. Як саме, я скинула в slack
2. У вас всі атрибути alt однакові, треба зробити різні
3. Кнопки навігації мають бути зроблені не через before, after а у вигляді іконок, теж кинула в слак
4. Стилі для кнопок:
.navigation {
  display: flex;
  justify-content: center;
  align-items: start;
  gap: 12px;
}

.navigation-btn {
  cursor: pointer;
  border: 1px solid rgba(250, 250, 250, 0.5);
    border-radius: 50%;
    padding: 14px;
    width: 52px;
    height: 52px;

    display: flex;
      align-items: center;
      justify-content: center;

      background-color: transparent;

      transition: border-color 250ms ease-in-out;
}

.navigation-btn:hover {
  border-color: #ed3b44;
}

.navigation-btn:hover .swiper-icon {
  stroke: #ed3b44;
}


.swiper-icon {
  flex-shrink: 0;
  fill: none;
  stroke: #fafafa;

  transition: stroke 250ms ease-in-out;
}
5. Для класу .projects-swiper-slide забрати width i background-color ЗІ ВСІХ МЕДІАПРАВИЛ
6. Для .project-tech-skills залишаємо тільки такі стилі : 
{
    padding: 32px;
    background-color: #fafafa;
}
7. Для .project-link стилі мають виглядати:  
{
display: flex;
justify-content: center;
align-items: center;

border-radius: 60px;
padding: 13px 32px;
width: 141px;
height: 45px;
background-color: #ed3b44;

font-weight: 500;
}
8. В кожну li з класом tech-skills-item вкладаємо р з класом tech-skills-text
9. Даємо їм такі стилі:
.tech-skills-item {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 45px;

border: 1px solid rgba(28, 29, 32, 0.2);
border-radius: 60px;
padding: 13px 18px;
}

.tech-skills-text {
  color: #1c1d20;
}
10. З класу .projects-text забираємо font-family, font-weight i padding-right
11. В класі .project-image має бути padding: 100px 16px;

ПЛАНШЕТНА ВЕРСІЯ

1. Стилі кнопок:
 .navigation {
  gap: 20px;
}

.navigation-btn {
  padding: 18px;
    width: 68px;
    height: 68px;
}

.swiper-icon {
  width: 32px;
  height: 32px;
}
2. Для класу .projects-swiper-slide додати margin-bottom: 64px;
3. Для класу .project-tech-skills залишити тільки:
 {
    padding: 64px;
}
4. Для .project-link забрати margin-bottom: 64px;
5. Для класу .tech-skills-item робимо стилі:
{
  height: 55px;
  padding: 18px;
}
6. Для класу .projects-text забрати padding і додати width: 494px;

ДЕСКТОПНА ВЕРСІЯ

1. Для класу .projects-swiper-slide додати width: 1376px; і забрати flex-direction: row;
2. Для класу .tech-skills-list додати margin-bottom: 223px;
3. Для класу .project-image додати padding: 120px 37px; i border-radius: 0 24px 24px 0;

2024-12-22 19:23 UTC, Dutko-Diana requested changes
1. Щоб робити кнопки 'задізейбленими' при останньому слайді треба в джава скріпт у властивість navigation: дописати disabledClass: 'swiper-button-disabled'. Тобто:
```
navigation: {
    nextEl: '.button-next',
    prevEl: '.button-prev',
    disabledClass: 'swiper-button-disabled',
  },
```
2. Для стилю цієї кнопки додати в css такий код:
```
.swiper-button-disabled {
  border-color: rgba(250, 250, 250, 0.2);
}

.swiper-button-disabled:hover {
  cursor: not-allowed;
  border-color: rgba(250, 250, 250, 0.2);
}

.swiper-button-disabled .swiper-icon {
  stroke: #3b3b3b;
}
.swiper-button-disabled:hover .swiper-icon {
  stroke: #3b3b3b;
}
```
3. В червоній кнопці краще дати посилання на репозиторій, а не на живу сторінку: (https://github.com/Dutko-Diana/super-team-project) і потрібно зробити ховер на неї, він єна макеті)
4. Щоб можна було сенсором гортати додати до свайпера в js:
```
scrollbar: {
    el: '.swiper-scrollbar',
  },
  mousewheel: true,
```
5. Я замітила, що у тебе слайди зроблені через div-и, але по тз їх треба зробити через список з лішками, тому ці теги теж треба замінити

Дуже гарна робота! ❤️

2024-12-23 11:17 UTC, tetiana-haievska commented
Виправила.
1. disabledClass: прописано.
2. стилі прописано.
3. посилання замінено.
4. scrollbar: додано.
5. слайди виправила, зробила через список (напочатку також так робила, але потім захотілося через div )) )

Дуже дякую за допомогу ) ❤️
Надсилаю на перевірку.

2024-12-23 11:42 UTC, Dutko-Diana approved these changes
Все працює, теж дякую за гарну співпрацю! ❤️

2024-12-23 11:42 UTC, merged