hero markup and css
Dutko-Diana/super-team-project pull request #7
Opened 2024-12-21 18:36 UTC by veronikavatsyak

2024-12-21 21:42 UTC, Dutko-Diana requested changes
HEADER

1. Потрібно трохи змінити розмітку логотипа, а саме забрати div і віддати його клас посиланню. Також помістити текст всередину посилання. Ось таким чином:
```
<a class="logo-container" href="./index.html">
        <img
          srcset="
            ../images/logo-image/logo-image.png    1x,
            ../images/logo-image/logo-image@2x.png 2x
          "
          alt="jefferson-image"
          width="80"
          height="80"
        />
        jefferson*
      </a>
```
2. Для кнопки-бургера забрати одну крапку зі шляху до іконки
3. В розмітці для іконки вказати розміри: `<svg class="burger" width="28" height="28">`
4. Для класу .menu-button стилі мають виглядати так: 
```
{
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: transparent;
    border: none;
    width: 28px;
    height: 28px;
}
```
5. Для класу .burger стилі мають бути: 
```
{
    stroke: #fafafa;
    flex-shrink: 0;
}
```
ПЛАНШЕТНА ВЕРСІЯ
1. Треба зробити медіаправило для картинки 2х:
```
@media screen and (-webkit-min-device-pixel-ratio: 2),
        (min-resolution: 2dppx),
        (min-resolution: 192dpi) {
            .hero {
                background-image: url('../images/hero-background/hero-tab@2x.png');
            }
        }
```
2. Для класу  .menu стилі мають бути: 
```
{
        border: none;
        font-weight: 500;
        background-color: transparent;
    }
```
3. Забрати в html повністю тег div з класом order-container і його стиль теж забрати
4. Відповідно для класу .order задати display: none;

HERO

2. Щоб відображались картинки фону треба взяти посилання в лапки і додати ще одну крапку на початок, бо без неї не відображається. Формат:
`background-image: url('../images/hero-background/hero-mob.png');`
3. В посилання на гіт хаб треба додати посилання саме на наш спільний репозиторій: ((https://github.com/Dutko-Diana/super-team-project))
5. Стилі для класу .hero мають бути: 
```
{
    position: relative;
    padding-top: 64px;
        background-size: 320px;
        background-repeat: no-repeat;
        background-position: left top;
        background-image: url('../images/hero-background/hero-mob.png');
        padding: 281px 0 32px;
}
```
6. Для класу .hero-title забрати margin-top: 169px; width: 343px; і text-align: left;
7. Для правильного відображення заголовку треба використати br:
```
<h1 class="hero-title">
      Hello. <br />
      I’m Fullstack developer Lloyd Jefferson.
    </h1>
```
8. Для класу .contacts-wrapper замінити значення align-items на center;
9. Для класу .hero-list забрати margin-bottom: 32px;
10. Для класу .hero-email стилі мають бути: 
```
{
    display: flex;
    width: 178px;
    height: 37px;
    border: 1px solid rgba(250, 250, 250, 0.2);
    border-radius: 60px;
    padding: 10px 12px;
    font-size: 14px;
    align-items: center;
    justify-content: center;
}
```
ПЛАНШЕТНА ВЕРСІЯ
1. Для класу .hero додати background-size: 581px; і padding: 300px 0 32px;
2. Для класу .hero-title залишити тільки font-size i margin-bottom
4. Для класу .hero-email додати height: 55px;

ДЕСКТОПНА ВЕРСІЯ

1. Для класу .hero додати background-size: 728px; і ЗАБРАТИ padding-top: 96px;

2024-12-22 04:29 UTC, veronikavatsyak commented
додала всі зміни в hero. для header окрема гілка)

2024-12-22 08:46 UTC, Dutko-Diana requested changes
Все гарно виправлено - єдиний момент я пропустила з посиланнями. Потрібно для кожного стилю з класом .hero-item дописати a. Ось так має виглядати:
МОБІЛЬНА ВЕРСІЯ:
```
.hero-item a {
    display: flex;
        align-items: center;
        justify-content: center;
        border: 1px solid rgba(250, 250, 250, 0.2);
        border-radius: 60px;
        padding: 10px 12px;
        width: 37px;
        height: 37px;
        font-size: 14px;
transition: border-color 250ms ease-in-out, color 250ms ease-in-out;
}
```
ПЛАНШЕТНА ВЕРСІЯ:
```
.hero-item a {
        padding: 18px 20px;
        width: 55px;
        height: 55px;
        font-size: 16px;
    }
```
Це потрібно для того, щоб посилання працювало на цілому кружечку, а не тільки на буквах.
Також додай ховери для зміни кольору тексту і рамки всіх посилань і електронки на #ed3b44;

```
.hero-item a:hover,
.hero-item a:focus {
    border-color: #ed3b44;
    color: #ed3b44;
}

```

```
.hero-email {
        display: flex;
        width: 178px;
        height: 37px;
        border: 1px solid rgba(250, 250, 250, 0.2);
        border-radius: 60px;
        padding: 10px 12px;
        font-size: 14px;
        align-items: center;
        justify-content: center;
        transition: border-color 250ms ease-in-out, color 250ms ease-in-out;
    }

.hero-email:hover,
.hero-email:focus {
    border-color: #ed3b44;
    color: #ed3b44;
}
```

2024-12-22 18:46 UTC, veronikavatsyak commented
додала зміни для hero)

2024-12-22 19:29 UTC, Dutko-Diana approved these changes
Чудово! Все гарненько 😍😍😍 🥇

2024-12-22 19:30 UTC, merged