header markup and css correcting errors
Dutko-Diana/super-team-project pull request #8
Opened 2024-12-22 03:58 UTC by veronikavatsyak

додаю зміни до хедера окремо в гілці header

2024-12-22 08:51 UTC, Dutko-Diana requested changes
Теж все дуже гарно і знову я недогледіла - треба з класу .menu-item забрати `text-decoration: underline;`
І все) 👍

2024-12-22 20:02 UTC, veronikavatsyak commented
додала зразу файлик js

2024-12-22 20:49 UTC, Dutko-Diana requested changes
Треба трошки змінити код, щоб реалізувати плавну появу меню:
1. з хтмл забрати клас is-hidden
2. B css додати ось такі стилі (деякі класи залишаються, їх просто треба доповнити):
```
.menu-list {
            display: flex;
                flex-direction: column;
                gap: 5px;
                align-items: center;
                justify-content: center;
            opacity: 0;
            visibility: hidden;
            transition: opacity 250ms ease-in-out, visibility 250ms ease-in-out;
            /* Плавний перехід для прозорості та затримка для visibility */
        }
    
        /* Клас, який додається при показі меню */
        .menu-list.show {
            opacity: 1;
            visibility: visible;
            transition: opacity 250ms ease-in-out;
            /* Плавне з'явлення */
        }
    
        /* Стилі для елементів меню */
        .menu-item {
            font-weight: 500;
            font-size: 16px;
            transition: color 250ms linear;
        }
```
3. В джава скрипт трохи поміняти код:
```
const menu = document.querySelector('.menu');
const menuList = document.querySelector('.menu-list');

menu.addEventListener('click', onClick);
document.addEventListener('click', onDocumentClick);

function onClick(event) {
  event.preventDefault();
  menuList.classList.toggle('show'); // Заміна класу 'is-hidden' на 'show'
  const links = document.querySelectorAll('.menu-list a');
  links.forEach(link => {
    link.addEventListener('click', handleClicks);
  });
}

function onDocumentClick(event) {
  if (!menu.contains(event.target) && !menuList.contains(event.target)) {
    menuList.classList.remove('show'); // Видалення класу 'show' при кліку поза меню
  }
}

function handleClicks(event) {
  event.preventDefault();
  const sectionId = event.target.getAttribute('href').substring(1);
  const section = document.getElementById(sectionId);
  if (section) {
    section.scrollIntoView({
      behavior: 'smooth',
      block: 'start',
    });
  }
  menuList.classList.remove('show'); // Закриття меню після кліку на лінк
}
```

2024-12-23 13:27 UTC, Dutko-Diana approved these changes
Гарно зроблено, приймаю хедер) 👌 🥇

2024-12-23 13:27 UTC, merged