fotrv1
Dutko-Diana/super-team-project pull request #9
Opened 2024-12-22 16:39 UTC by Mukuta0Pusmenski

написав весь штмл та цсс з розміткою і трохи джави але неповністю(тпм прописана тіки кнопка закриття модалки аби раз по зраз не ховати її через код)

2024-12-22 17:27 UTC, Dutko-Diana requested changes
1. Видалити теги head, html, script. Має залишитись тільки footer i div-модалка

```
<footer class="footer">
  <div class="container footer-content">
    <div class="image-and-text">
      <a href="../index.html">
        <img
          srcset="
            ../images/logo-image/logo-image.png    1x,
            ../images/logo-image/logo-image@2x.png 2x
          "
          alt="logo link"
          class="footer-image"
          width="44"
          height="44"
        />
      </a>
      <h2 class="footer-title">
        Let’s <span class="work">work</span> together
      </h2>
    </div>
    <form class="contact-form" id="contactForm">
      <input
        type="email"
        placeholder="clients@gmail.com"
        class="input-info"
        pattern="^\w+(\.\w+)?@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$"
        required
      />
      <input placeholder="comments" required class="input-info"></input>
      <button type="submit" class="send-button">Send</button>
    </form>
    <div class="contact-info">
      <a href="mailto:lloydjefferson@gmail.com" class="contact-link"
        >lloydjefferson@gmail.com</a
      >
      <a href="tel:+380111111111" class="contact-link">+380 11 1111 11 11</a>
    </div>
  </div>
</footer>

<!-- Модальне вікно -->
<div id="thankYouModal" class="modal">
  <div class="modal-content">
    <button type="button" class="close-button">
<svg class="close-button-icon" width="22" height="22">
    <use href="./images/sprite.svg#close"></use>
</svg>
    </button>
    <h2 class="modal-hed">Thank you for your interest in cooperation!</h2>
    <p class="modal-p">
      The manager will contact you shortly to discuss further details and
      opportunities for cooperation. Please stay in touch.
    </p>
  </div>
</div>
```

2024-12-23 18:08 UTC, Mukuta0Pusmenski commented
замінив деякі стилі та трохи штмл а так наче все

2024-12-23 21:34 UTC, Dutko-Diana requested changes
1. В js var замінити на let 
2. Ось це забрати повністю:
```
.container {
    padding: 20px;
    background-color: #444;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
}
```
3. Для класу 
```
.footer {
    padding-top: 64px;
}
```
4. Для класу 
```
.footer-content {
    padding: 32px 16px;
}
```
5. Видалити з розмітки тег `<div class="image-and-text">`
6. Заголовок написати ось таким чином: 
```
<h2 class="footer-title">Let’s <span class="work">work</span> <br> <span class="together">together</span></h2>
```
7. Зробити такі стилі:
```
.footer-img-text {
    margin-bottom: 107px;
}

.footer-title {
font-weight: 500;
    font-size: 40px;
    line-height: 1;
    letter-spacing: -0.03em;
    text-transform: uppercase;
    position: relative;
}

.together {
    position: absolute;
    left: -52px;
        top: 48px;
}
```
8. Видалити повністю: 
```
.footer-img-text h1 {
    margin: 0;
    padding: 0;
    text-align: left;
}
```
9. Видалити зовсім стилі для класу .footer-image 
10. Стилі для form.contact-form: 
```
{
    margin-bottom: 64px;
}
```
11. Відредагувати стилі для інпутів(забрати textarea, бо її нема в розмітці):
```
input {
    padding-bottom: 20px;
    border: none;
    border-bottom: 1px solid rgba(250, 250, 250, 0.2);
    background-color: transparent;
    font-weight: 500;
        font-size: 16px;
        line-height: 1.5;
        letter-spacing: -0.02em;
        color: #fafafa;
    width: 100%;
margin-bottom: 16px;
}

input:focus {
    outline: none;
    border-bottom: 1px solid rgba(250, 250, 250, 0.5);
}
```
12. Стилі для кнопки:
```
.send-button {
    background-color: #ED3B44;
    border: none;
    border-radius: 50%;
    width: 100px;
    height: 100px;
    font-weight: 500;
    letter-spacing: -0.02em;
    cursor: pointer;
    transition: background-color 0.3s;
    margin-top: 16px;
}
```
ДОДАТИ ХОВЕР ДЛЯ КНОПКИ
13. Стилі для:
```
.contact-info {
    display: flex;
    justify-content: flex-start;
    align-items: center;
    gap: 4px
}
```
14. Стилі для:
```
.contact-link {
    border: 1px solid rgba(250, 250, 250, 0.2);
    border-radius: 60px;
    padding: 10px 20px;
    text-decoration: none;
    height: 37px;
    font-weight: 500;
        font-size: 14px;
        letter-spacing: -0.02em;
        display: flex;
        justify-content: center;
        align-items: center;
}
```
15. Видалити повність стиль:
```
.contact-details p {
    margin-top: 10px;
}
```

ПЛАНШЕТНА ВЕРСІЯ

1. Медіапрвило має виглядати: `@media screen and (min-width: 768px)`
2. Прописати:
```
.footer {
    padding-top: 96px;
}
```
3. Прописати:
```
.footer-content {
        padding: 80px 32px 169px;
    }

    .footer-img-text {
        gap: 20px;
        margin-bottom: 89px;
    }
```
4. Прописати:
```
.footer-image {
        width: 70px;
        height: 70px;
    }
```
5. Стилі для:
```
.footer-title {
    font-size: 64px;
    }
```
6. Прописати:
```
.together {
        left: -90px;
        top: 74px;
    }
```
7. Стилі для:
```
form.contact-form {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-bottom: 18px;
    }
```
ВСІ РЕШТА ДЛЯ ЦЬОГО КЛАСУ ПОВИДАЛЯТИ З ПЛАНШЕТА, їх там чомусь багато однакових
8. Видалити:
```
 .contact-info {
        flex: 1 1 30%;
        /* Третій стовпець */
        display: flex;
        /* flex-direction: column;
        align-items: flex-start; */
    }

.input-info {
        font-family: "Inter Tight", sans-serif;
            font-weight: 500;
            font-size: 16px;
        
            line-height: 150%;
            letter-spacing: -0.02em;
            color: rgba(250, 250, 250, 0.6);
    }

.input-info {
        width: 245px;
        height: 44px;
    }
```
9. Для класу:
```
.input-info {
        margin-right: 32px;
        margin-bottom: 0;
    }
```
10. Для класу:
```
.send-button {
        width: 150px;
        height: 150px;
        flex-shrink: 0;
        margin-top: 0;
    }
```
11. Для класу:
```
.contact-info {
        gap: 8px;
    }
```
12. Видалити:
```
.footer-img-text {
        flex: 1 1 30%;
        align-items: flex-start;
    }

    input {
        margin-right: 10px;
    }
```

ДЕСКТОПНА ВЕРСІЯ

1. Медіаправило має виглядати: `@media screen and (min-width: 1440px)`
2. Стилі для:
```
.footer {
            padding-top: 164px;
        }

.footer-content {
        padding: 80px 196px 169px;
    }
```

Позабирати всюди коментарі з коду і зайві стиоі, як іповторюються по декілька разів. Уважно, будь ласка, кожен крок виправити!😉

2024-12-24 20:00 UTC, Mukuta0Pusmenski commented
зробив все що ти писала але в слакі розписав проблеми та пиатння

2024-12-24 21:40 UTC, Mukuta0Pusmenski commented
почав ролботу над джс

2024-12-25 10:30 UTC, Dutko-Diana approved these changes

2024-12-25 10:30 UTC, merged